// Controlled presentation comparison: same actual input sequence and rules, three local treatments.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('evidence/local/signature',{recursive:true});const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu']});const runs=[];
async function walk(p,x,z){await p.keyboard.press('KeyR');for(let i=0;i<100;i++){const a=await p.evaluate(()=>window.__orrery.position),dx=x-a.x,dz=z-a.z;if(Math.hypot(dx,dz)<.8)return;const ks=[...(Math.abs(dx)>.45?[dx>0?'KeyD':'KeyA']:[]),...(Math.abs(dz)>.45?[dz>0?'KeyS':'KeyW']:[])];for(const k of ks)await p.keyboard.down(k);await p.waitForTimeout(180);for(const k of ks)await p.keyboard.up(k)}throw Error('navigation blocked')}
async function accept(p,x,z){await walk(p,x,z);await p.keyboard.press('KeyE');await p.click('[data-action=accept]')}
try{for(const treatment of ['pages','spirit','eclipse']){const c=await b.newContext({viewport:{width:1280,height:720},recordVideo:{dir:'evidence/local/signature',size:{width:1280,height:720}}});const p=await c.newPage();p.setDefaultTimeout(15000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5180');await p.waitForFunction(()=>window.__orrery?.loadedAtMs>0,null,{timeout:60000});await p.click('[data-action=begin]');await p.click('[data-action=journal]');await p.click('.laboratory summary');await p.selectOption('#signature-treatment',treatment);await p.click('[data-action=close]');await accept(p,-3,6);await walk(p,3,7);await accept(p,4,1);await walk(p,3,-1);await accept(p,0,-4);
const before=await p.evaluate(()=>window.__orrery.resources);await p.click('[data-spell=mark]');await p.click('[data-action=confirm]');await p.waitForFunction(()=>!window.__orrery.playing,null,{timeout:15000});await p.click('[data-spell=unfold]');const start=Date.now();await p.click('[data-action=confirm]');await p.waitForFunction(()=>window.__orrery.playing);const committed=await p.evaluate(()=>window.__orrery.battle);const frames=[];for(let i=0;i<3;i++){await p.waitForTimeout(560);await p.screenshot({path:`evidence/local/signature/${treatment}-${i}.png`});frames.push(await p.evaluate(()=>({resources:window.__orrery.resources,effects:window.__orrery.effectChildren,frameMs:window.__orrery.frameMs}))) }await p.waitForFunction(()=>!window.__orrery.playing,null,{timeout:15000});assert.deepEqual(await p.evaluate(()=>window.__orrery.battle),committed);assert.equal(await p.evaluate(()=>window.__orrery.effectChildren),0);const clean={...committed,id:'comparison'};runs.push({treatment,outcome:clean,durationMs:Date.now()-start,before,frames,after:await p.evaluate(()=>window.__orrery.resources),errors});assert.deepEqual(errors,[]);await c.close()}
assert.deepEqual(runs[0].outcome,runs[1].outcome);assert.deepEqual(runs[1].outcome,runs[2].outcome);await writeFile('evidence/signature-comparison.json',JSON.stringify({date:new Date().toISOString(),actualInputs:true,stateFixtures:false,identicalAuthoritativeOutcomes:true,runs,caveat:'Local recording run, not controlled GPU performance. Timings include screenshot overhead.'},null,2));console.log('Three presentations: identical committed result and natural completion, no page errors.')
}finally{await b.close()}
