import * as T from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone } from 'three/addons/utils/SkeletonUtils.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';

export type Position={x:number;z:number;yaw:number};
const rand=(n:number)=>{const v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v)};
export class World {
 scene=new T.Scene(); camera=new T.PerspectiveCamera(49,1,.1,150); renderer:T.WebGLRenderer;
 player=new T.Group(); partner=new T.Group(); npc=new T.Group(); environment=new T.Group(); enemyGroup=new T.Group(); fx=new T.Group();
 position:Position={x:0,z:10,yaw:Math.PI}; remote:Position={x:1,z:10,yaw:Math.PI};
 yaw=0; pitch=.27; distance=9; sensitivity=1; reduced=false; low=false; stage=0; battle=false; active=true; moving=false;
 target=new T.Vector3(0,1.8,10); keys=new Set<string>(); bindings={forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD',interact:'KeyE',recenter:'KeyR',journal:'KeyJ',confirm:'Enter'};
 frames:number[]=[]; loadedAt=0; loadingErrors:string[]=[]; mixers:T.AnimationMixer[]=[]; actions:T.AnimationAction[][]=[]; actorMeshes=new Map<string,T.Object3D>();
 private drag:{x:number;y:number}|null=null; private clock=0; private last=performance.now(); private effectTime=0; private effectDuration=0; private effectKind=''; private effectTarget=new T.Vector3(); private orrery?:T.Object3D; private awakened=new T.Group(); private doorwayLight=new T.Group(); private casting=''; identityColor='#2b7f88'; partnerColor='#bc745e';
 private stone:T.MeshStandardMaterial; private gold:T.MeshStandardMaterial; private green:T.MeshStandardMaterial; private lamp:T.MeshStandardMaterial;
 constructor(public canvas:HTMLCanvasElement, public onMove:(p:Position)=>void) {
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
  this.scene.background=new T.Color('#b9d7d6');this.scene.fog=new T.Fog('#b9d7d6',35,110);
  this.stone=this.material('#eee0bd','stone');this.gold=this.material('#caa760','metal');this.green=this.material('#739775','leaf');this.lamp=new T.MeshStandardMaterial({color:'#ffd99a',emissive:'#ffbe64',emissiveIntensity:.8,roughness:.6});
  this.scene.add(new T.HemisphereLight('#e6f2ff','#8d845d',1.8));const sun=new T.DirectionalLight('#fff1cf',2.8);sun.position.set(-15,24,13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:30,bottom:-30,near:.5,far:80});sun.shadow.bias=-.0005;sun.shadow.normalBias=.035;this.scene.add(sun);sun.target.position.set(0,0,-8);this.scene.add(sun.target);
  this.scene.add(this.environment,this.player,this.partner,this.npc,this.enemyGroup,this.fx);this.partner.visible=false;this.npc.position.set(-3,0,6);this.buildEnvironment();this.batchStatic();this.buildProxyWizard(this.player,'#286d76');this.buildProxyWizard(this.npc,'#b26655');this.buildProxyWizard(this.partner,'#b26655');
  this.player.position.set(0,0,10);this.player.rotation.y=Math.PI;this.camera.position.set(0,4.2,18);this.camera.lookAt(this.target);this.resize();window.addEventListener('resize',()=>this.resize());
  canvas.addEventListener('pointerdown',e=>{if(!this.active||this.battle)return;this.drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!this.drag||!this.active)return;this.yaw-=(e.clientX-this.drag.x)*.006*this.sensitivity;this.pitch=T.MathUtils.clamp(this.pitch+(e.clientY-this.drag.y)*.004*this.sensitivity,.18,.85);this.drag={x:e.clientX,y:e.clientY}});canvas.addEventListener('pointerup',()=>this.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();if(this.active)this.distance=T.MathUtils.clamp(this.distance+e.deltaY*.012,5,13)},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
  window.addEventListener('blur',()=>{this.keys.clear();this.drag=null});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.active=false;document.getElementById('toast')!.textContent='Graphics paused. Reload to restore your last saved state.'});
  this.loadAssets();requestAnimationFrame(this.frame);
 }
 material(color:string,kind='plain') {const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=color;ctx.fillRect(0,0,128,128);for(let i=0;i<170;i++){ctx.fillStyle=i%2?'#ffffff0c':'#203c3510';ctx.beginPath();ctx.ellipse(rand(i)*128,rand(i+900)*128,4+rand(i+30)*17,1+rand(i+40)*4,rand(i+100)*2,0,Math.PI*2);ctx.fill()}if(kind==='stone'){ctx.strokeStyle='#716b4930';ctx.lineWidth=1;for(let y=0;y<128;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(128,y);ctx.stroke();for(let x=(y%64?24:0);x<128;x+=48){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+32);ctx.stroke()}}}const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;map.wrapS=map.wrapT=T.RepeatWrapping;return new T.MeshStandardMaterial({map,roughness:kind==='metal'?.55:.92,metalness:kind==='metal'?.32:0})}
 mesh(geo:T.BufferGeometry,mat:T.Material,x:number,y:number,z:number,parent:T.Object3D=this.environment){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 box(w:number,h:number,d:number,mat:T.Material,x:number,y:number,z:number,p?:T.Object3D){return this.mesh(new T.BoxGeometry(w,h,d),mat,x,y,z,p)}
 sphere(r:number,mat:T.Material,x:number,y:number,z:number,p?:T.Object3D){return this.mesh(new T.SphereGeometry(r,12,8),mat,x,y,z,p)}
 ring(r:number,t:number,mat:T.Material,x:number,y:number,z:number,p?:T.Object3D){const m=this.mesh(new T.TorusGeometry(r,t,6,48),mat,x,y,z,p);m.rotation.x=-Math.PI/2;return m}
 private buildEnvironment(){
  const grass=this.material('#8ca978','leaf'), path=this.material('#d8c59e','stone'), roof=this.material('#426875','stone'), wood=this.material('#795d43','stone'), dark=this.material('#254958'), pink=this.material('#df8e89');
  this.box(180,.6,180,grass,0,-.4,-15);this.box(26,.12,39,path,0,-.05,-3.5);
  // Broad, irregular paving with quiet variation, instanced to keep draw calls bounded.
  const tiles=new T.InstancedMesh(new T.BoxGeometry(1.22,.035,1.23),path,600);const mat=new T.Matrix4();let count=0;
  for(let z=-21;z<16;z+=1.3)for(let x=-12.4;x<13;x+=1.3){mat.compose(new T.Vector3(x+(Math.round(z*10)%2)*.15,.036,z),new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),(rand(count)-.5)*.065),new T.Vector3(.92+rand(count+2)*.08,1,.96));tiles.setMatrixAt(count,mat);tiles.setColorAt(count,new T.Color().setHSL(.11,.24,.61+rand(count)*.17));count++}tiles.count=count;tiles.receiveShadow=true;this.environment.add(tiles);
  for(const x of [-14,14]){this.box(.65,1.4,43,this.stone,x,.7,-4);this.box(.85,.18,43,this.gold,x,1.43,-4);for(let z=-24;z<18;z+=5){this.box(1,1.8,1,this.stone,x,.9,z);this.sphere(.28,this.gold,x,1.98,z)}}
  // College wings: plaster, deep openings, carved arch surrounds, pitched roofs.
  for(const x of [-11,11]){for(const z of [-13,-5,3]){this.box(4.6,4.8,6.8,this.stone,x,2.4,z);this.box(4.85,.24,7.1,this.gold,x,4.72,z);const r=this.mesh(new T.CylinderGeometry(0,3.75,2.1,4),roof,x,5.83,z);r.rotation.y=Math.PI/4;r.scale.z=1.35;
    const frontX=x<0?x+2.34:x-2.34;for(const zz of [z-1.65,z+1.65]){const g=new T.Group();g.position.set(frontX,0,zz);g.rotation.y=x<0?Math.PI/2:-Math.PI/2;this.environment.add(g);this.box(1.2,2.75,.08,dark,0,1.7,0,g);this.mesh(new T.CylinderGeometry(.6,.6,.09,20,1,false,0,Math.PI),this.gold,0,3.05,0,g).rotation.x=Math.PI/2;this.box(.12,2.7,.15,this.gold,-.66,1.68,0,g);this.box(.12,2.7,.15,this.gold,.66,1.68,0,g);this.box(1.5,.13,.2,this.gold,0,.34,0,g);for(let j=0;j<3;j++)this.box(1.1,.05,.15,this.gold,0,1+j*.7,.07,g);this.box(.05,2.5,.15,this.gold,0,1.7,.07,g)}
   }}
  // Garden borders leave a clear central route and little pockets to explore.
  for(const x of [-6.6,6.6])for(const z of [9,2,-6,-13]){this.box(2.5,.27,3.8,this.stone,x,.15,z);this.box(2.25,.1,3.55,grass,x,.33,z);for(let i=0;i<16;i++){const px=x+(rand(i+z*4)-.5)*2,pz=z+(rand(i+100+z*4)-.5)*3;const stem=this.mesh(new T.CylinderGeometry(.025,.035,.4,5),this.green,px,.55,pz);stem.castShadow=false;const fl=this.sphere(.13,pink,px,.79,pz);fl.scale.set(1.5,.65,1.5);fl.castShadow=false}}
  for(const x of [-7.3,7.3])for(const z of [13,-1,-10,-19])this.tree(x,z,3.7+rand(z)*1.5,wood,grass);
  for(let i=0;i<36;i++){const side=i%2?1:-1;this.tree(side*(19+rand(i)*20),-45+rand(i+90)*76,4+rand(i+25)*7,wood,grass)}
  for(let i=0;i<12;i++){const m=this.sphere(15+rand(i)*13,this.material(i%2?'#759996':'#98b2a1'),-75+i*13,-4,-65-rand(i+25)*20);m.scale.set(1,1.2,1)}
  // Human touches: benches, cups, books, pots and pennants.
  for(const x of [-4.8,4.8]){this.box(1.7,.13,.6,wood,x,.55,11);this.box(1.7,.65,.12,wood,x,.95,11.3);for(const dx of [-.65,.65])this.box(.12,.6,.5,dark,x+dx,.28,11);this.box(.4,.08,.27,pink,x+.2,.66,11);this.box(.32,.08,.3,roof,x+.1,.75,11)}
  for(const [x,z] of [[4,1],[-5,-9]]){this.mesh(new T.CylinderGeometry(.42,.58,.65,10),wood,x,.33,z);this.ring(.4,.035,this.gold,x,.69,z)}
  this.sphere(.23,this.lamp,4,1.25,1);this.ring(.38,.028,this.gold,4,1.25,1).rotation.x=.2;this.box(.68,.1,.46,roof,-5,.85,-9).rotation.z=.15;
  for(const x of [-4.5,4.5])for(const z of [6,-4,-15]){this.mesh(new T.CylinderGeometry(.05,.09,2.4,8),dark,x,1.2,z);this.box(.35,.5,.35,this.lamp,x,2.5,z);this.mesh(new T.ConeGeometry(.32,.3,4),roof,x,2.9,z);}
  const arch=new T.Shape();arch.absarc(0,0,2.5,0,Math.PI,false);arch.absarc(0,0,2.18,Math.PI,0,true);const a=this.mesh(new T.ExtrudeGeometry(arch,{depth:.5,bevelEnabled:false}),this.stone,0,3.0,18.8);a.castShadow=true;for(const x of [-2.35,2.35])this.box(.35,3,.55,this.stone,x,1.5,19);this.ring(3.6,.045,this.gold,0,.11,-14);
  this.makeEnemies();
  this.awakened.position.set(0,9.3,-23);this.scene.add(this.awakened);for(let i=0;i<3;i++){const ring=this.ring(2.0+i*.2,.035,this.gold,0,0,0,this.awakened);ring.rotation.set(i*.8,.3,i*.7)}this.sphere(.5,this.lamp,0,0,0,this.awakened);for(let i=0;i<14;i++)this.sphere(.06,this.lamp,Math.cos(i)*2.7,Math.sin(i*2)*1.5,Math.sin(i)*2.7,this.awakened);this.awakened.visible=false;
  this.doorwayLight.position.set(0,0,-18.9);this.scene.add(this.doorwayLight);const aura=new T.MeshBasicMaterial({color:'#ffdb82',transparent:true,opacity:.16,depthWrite:false});const glow=this.sphere(1.35,aura,0,1.9,0,this.doorwayLight);glow.scale.set(1,1.45,.2);const hoop=this.ring(1.4,.035,this.lamp,0,1.9,.1,this.doorwayLight);hoop.rotation.x=Math.PI/2;hoop.scale.y=1.3;for(let i=0;i<16;i++)this.sphere(.07,this.lamp,Math.cos(i)*1.7,1.8+Math.sin(i)*1.6,.3+Math.sin(i*3)*.4,this.doorwayLight);this.doorwayLight.add(new T.PointLight('#ffd899',18,14,2));this.doorwayLight.visible=false;
 }
 private tree(x:number,z:number,h:number,wood:T.Material,leaf:T.Material){const group=new T.Group();group.position.set(x,0,z);this.environment.add(group);this.mesh(new T.CylinderGeometry(.12,.23,h*.7,7),wood,0,h*.35,0,group);for(let i=0;i<4;i++){const m=this.sphere(h*.28,leaf,(rand(i+x)-.5)*h*.35,h*.65+rand(i+z)*h*.25,(rand(i+z+20)-.5)*h*.4,group);m.scale.set(.8,1.2,.8)}}
 private batchStatic(){this.environment.updateMatrixWorld(true);const batches=new Map<T.Material,{geos:T.BufferGeometry[];meshes:T.Mesh[]}>();this.environment.traverse(o=>{if(o instanceof T.Mesh&&!(o instanceof T.InstancedMesh)&&!Array.isArray(o.material)){let batch=batches.get(o.material);if(!batch){batch={geos:[],meshes:[]};batches.set(o.material,batch)}batch.geos.push(o.geometry.clone().applyMatrix4(o.matrixWorld));batch.meshes.push(o)}});for(const [material,batch] of batches){const geo=mergeGeometries(batch.geos);if(geo){const mesh=new T.Mesh(geo,material);mesh.castShadow=true;mesh.receiveShadow=true;this.environment.add(mesh);for(const source of batch.meshes){source.removeFromParent();source.geometry.dispose()}}for(const g of batch.geos)g.dispose()}}
 private buildProxyWizard(group:T.Group,color:string){const cloth=this.material(color), skin=this.material('#d7a580'), boots=this.material('#57433e');this.box(.56,.68,.33,cloth,0,1.07,0,group);for(const x of [-.17,.17]){this.box(.2,.55,.22,boots,x,.37,0,group);this.box(.24,.18,.4,boots,x,.09,.07,group);this.box(.17,.58,.2,cloth,x*2.1,1,0,group)}this.sphere(.24,skin,0,1.63,0,group);for(const x of [-.085,.085])this.sphere(.026,boots,x,1.66,.223,group);const brim=this.mesh(new T.CylinderGeometry(.5,.5,.06,24),cloth,0,1.85,0,group);brim.rotation.z=.09;this.mesh(new T.ConeGeometry(.31,.65,12),cloth,.03,2.14,0,group);this.box(.1,1.8,.1,this.gold,.48,.93,.1,group);this.sphere(.12,this.lamp,.48,1.88,.1,group)}
 private async loadAssets(){const loader=new GLTFLoader();try{const gltf=await loader.loadAsync('/assets/wizard.glb');for(const [i,group] of [this.player,this.npc,this.partner].entries()){group.clear();const obj=clone(gltf.scene);obj.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;{const materials=Array.isArray(o.material)?o.material:[o.material];o.material=materials.map(m=>{const n=m.clone();if(n.name.toLowerCase().includes('identity')&&'color'in n)(n as T.MeshStandardMaterial).color.set(i===1?'#bc745e':i===2?this.partnerColor:this.identityColor);return n});if(o.material.length===1)o.material=o.material[0]}}});group.add(obj);const mixer=new T.AnimationMixer(obj);this.mixers.push(mixer);const clips=gltf.animations;const idle=clips.find(c=>/idle/i.test(c.name)),walk=clips.find(c=>/walk/i.test(c.name)),cast=clips.find(c=>/cast/i.test(c.name));this.actions.push([idle?mixer.clipAction(idle):null,walk?mixer.clipAction(walk):null,cast?mixer.clipAction(cast):null].filter(Boolean) as T.AnimationAction[]);this.actions[i][0]?.play()}}catch(e){this.loadingErrors.push('Wizard: '+String(e))}
  try{const gltf=await loader.loadAsync('/assets/observatory.glb');gltf.scene.position.set(0,0,-23);gltf.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}if(o.name.toLowerCase().includes('orrery'))this.orrery=o});this.environment.add(gltf.scene)}catch(e){this.loadingErrors.push('Observatory: '+String(e));this.mesh(new T.CylinderGeometry(4.4,4.7,6,32),this.stone,0,3,-23);const dome=this.sphere(4.6,this.material('#446b7b'),0,6,-23);dome.scale.y=.7;for(let i=0;i<3;i++){const r=this.ring(2,.045,this.gold,0,10,-23);r.rotation.set(i,0,i*.8)}}this.loadedAt=performance.now();
 }
 private makeEnemies(){const paper=this.material('#e9d4a6');for(let j=0;j<2;j++){const g=new T.Group();g.name='moth'+(j+1);this.sphere(.22,this.gold,0,1.2,0,g);for(const side of [-1,1]){const s=new T.Shape();s.moveTo(0,0);s.lineTo(side*.85,.55);s.lineTo(side*.68,-.38);s.lineTo(0,-.1);const wing=this.mesh(new T.ShapeGeometry(s),paper,0,1.2,0,g);(wing.material as T.MeshStandardMaterial).side=T.DoubleSide;wing.name='wing'+side;}g.position.set(j===0?-1.2:2.2,0,-5);this.enemyGroup.add(g);this.actorMeshes.set(g.name,g)}const g=new T.Group();g.name='guardian';this.mesh(new T.CylinderGeometry(.5,.7,1.2,8),this.gold,0,1.3,0,g);this.sphere(.45,this.stone,0,2.18,0,g);for(const x of [-.18,.18])this.sphere(.08,this.lamp,x,2.22,.38,g);for(const x of [-.7,.7]){this.box(.32,1.1,.35,this.gold,x,1.2,0,g);this.box(.35,.65,.5,this.stone,x*.55,.4,0,g)}for(let i=0;i<3;i++){const r=this.ring(1.15,.032,this.gold,0,1.6,0,g);r.rotation.set(i*.7,.4,i*.4)}g.position.set(0,0,-15);this.enemyGroup.add(g);this.actorMeshes.set('guardian',g);this.actorMeshes.set('mage1',this.player);this.actorMeshes.set('mage2',this.partner)}
 setStage(stage:number){this.stage=stage;this.actorMeshes.get('moth1')!.visible=stage===2;this.actorMeshes.get('moth2')!.visible=false;this.actorMeshes.get('guardian')!.visible=stage===4;this.lamp.emissiveIntensity=stage>=5?2:stage>=2?1.2:.45;this.awakened.visible=this.doorwayLight.visible=stage===5}
 setBattle(battle:{actors:{id:string;hp:number;team:string}[]}|null,seat='mage1'){this.battle=!!battle;this.frameCamera();if(battle){const base=this.stage>=4?-14:-4;this.player.position.set(-1,0,base+4);this.player.rotation.y=Math.PI;this.partner.position.set(1,0,base+4);for(const a of battle.actors){const m=this.actorMeshes.get(a.id);if(m){m.visible=a.hp>0;if(a.id.startsWith('moth'))m.position.set(this.stage>=4?2.4:-1.2,0,base-1.4)}}this.target.set(0,1.1,base+1.4);this.partner.visible=battle.actors.some(a=>a.id==='mage2');if(seat==='mage2'){this.actorMeshes.set('mage2',this.player);this.actorMeshes.set('mage1',this.partner)}}}
 effect(spell:string,actor:string,target:string,duration:number){this.clearEffect();this.casting=actor;this.effectKind=spell;this.effectDuration=duration;this.effectTime=0;const at=this.actorMeshes.get(target)?.position??this.player.position;this.effectTarget.copy(at);this.fx.position.copy(at);const c=spell==='unfold'?'#9edddd':spell==='mend'||spell==='shelter'?'#ffe4a4':'#e9ab73';const mat=new T.MeshBasicMaterial({color:c,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false});if(spell==='unfold'){for(let i=0;i<12;i++){const sh=new T.Shape();sh.moveTo(0,0);sh.lineTo(.8,.55);sh.lineTo(1.4,0);sh.lineTo(.8,-.5);const page=this.mesh(new T.ShapeGeometry(sh),mat,Math.cos(i/12*Math.PI*2)*2,1.5+Math.sin(i)*.5,Math.sin(i/12*Math.PI*2)*2,this.fx);page.rotation.set(.5,i*.7,.5)}for(let i=0;i<3;i++){const r=this.ring(1.4+i*.6,.02,mat,0,1+i*.5,0,this.fx);r.rotation.z=i*.7}}else if(spell==='shelter'||spell==='mend'){const m=this.sphere(1.2,mat,0,1,0,this.fx);m.scale.set(1,1.2,1);mat.opacity=.22;this.ring(1.1,.04,this.gold,0,.12,0,this.fx)}else{for(let i=0;i<12;i++)this.sphere(.07+(i%3)*.04,mat,Math.cos(i)*.6,1+Math.sin(i*1.8)*.7,Math.sin(i)*.6,this.fx);this.ring(.8,.035,mat,0,.12,0,this.fx)}const caster=this.actorMeshes.get(actor);if(caster){caster.rotation.z=.04;const index=[this.player,this.npc,this.partner].indexOf(caster as T.Group);const cast=this.actions[index]?.[2];if(cast){cast.reset().setLoop(T.LoopOnce,1);cast.clampWhenFinished=true;cast.timeScale=.5;cast.play()}};}
 clearEffect(){this.fx.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();if(o.material instanceof T.MeshBasicMaterial)o.material.dispose()}});this.fx.clear();this.effectDuration=0;this.casting='';this.player.rotation.z=this.partner.rotation.z=0}
 recenter(){this.yaw=0;this.pitch=.27;this.distance=9}
 private frameCamera(){if(this.battle)this.camera.setViewOffset(innerWidth,innerHeight,0,innerHeight*.23,innerWidth,innerHeight);else this.camera.clearViewOffset()}
 setQuality(low:boolean){this.low=low;this.renderer.setPixelRatio(low?Math.min(devicePixelRatio,.85):Math.min(devicePixelRatio,1.5));this.resize()}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setPixelRatio(this.low?Math.min(devicePixelRatio,.85):Math.min(devicePixelRatio,1.5));this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 private blocked(x:number,z:number){if(Math.abs(x)>12.8||z>15.5||z< -19)return true;if(Math.abs(x)>8.25&&z<7)return true;for(const gx of [-6.6,6.6])for(const gz of [9,2,-6,-13])if(Math.abs(x-gx)<1.55&&Math.abs(z-gz)<2.13)return true;return false}
 private frame=(now:number)=>{requestAnimationFrame(this.frame);const elapsed=now-this.last;const dt=Math.min(elapsed/1000,.05);this.last=now;this.frames.push(elapsed);if(this.frames.length>1800)this.frames.shift();this.clock+=dt;this.moving=false;
  if(this.active&&!this.battle){const b=this.bindings;let dx=Number(this.keys.has(b.right))-Number(this.keys.has(b.left)),dz=Number(this.keys.has(b.back))-Number(this.keys.has(b.forward));if(dx||dz){const n=Math.hypot(dx,dz);dx/=n;dz/=n;const xx=(dx*Math.cos(this.yaw)+dz*Math.sin(this.yaw))*dt*3.8,zz=(-dx*Math.sin(this.yaw)+dz*Math.cos(this.yaw))*dt*3.8;if(!this.blocked(this.position.x+xx,this.position.z))this.position.x+=xx;if(!this.blocked(this.position.x,this.position.z+zz))this.position.z+=zz;this.position.yaw=Math.atan2(xx,zz);this.moving=true;this.onMove({...this.position})}this.player.position.set(this.position.x,0,this.position.z);this.player.rotation.y=this.position.yaw;this.target.lerp(new T.Vector3(this.position.x,1.8,this.position.z),1-Math.exp(-dt*7))}
  for(let i=0;i<this.mixers.length;i++){const walk=i===0&&this.moving;const acts=this.actions[i];if(acts.length>1){const casting=this.effectDuration>0&&this.actorMeshes.get(this.casting)===[this.player,this.npc,this.partner][i];acts[0].enabled=!walk&&!casting;acts[1].enabled=walk&&!casting;if(acts[2]){acts[2].enabled=casting;acts[2].timeScale=.5;}if(walk&&!acts[1].isRunning())acts[1].play()}this.mixers[i].update(dt)}
  if(!this.battle){this.partner.position.lerp(new T.Vector3(this.remote.x,0,this.remote.z),1-Math.exp(-dt*12));this.partner.rotation.y=this.remote.yaw}
  const d=this.battle?15:this.distance,angle=this.battle?.2:this.yaw,pitch=this.battle?.56:this.pitch;const desired=new T.Vector3(this.target.x+Math.sin(angle)*d*Math.cos(pitch),this.target.y+Math.sin(pitch)*d,this.target.z+Math.cos(angle)*d*Math.cos(pitch));this.camera.position.lerp(desired,1-Math.exp(-dt*(this.reduced?20:5)));this.camera.lookAt(this.target);
  for(const id of ['moth1','moth2']){const moth=this.actorMeshes.get(id)!;moth.position.y=.18+Math.sin(this.clock*2)*.15;moth.children.forEach((c,i)=>{if(c.name.startsWith('wing'))c.rotation.y=Math.sin(this.clock*6)*.45*(i%2?1:-1)})}
  if(this.stage===5){if(this.orrery)this.orrery.rotation.y+=dt*.12;this.awakened.rotation.y+=dt*.25}
  if(this.effectDuration){this.effectTime+=dt;const t=this.effectTime/this.effectDuration;this.fx.rotation.y+=dt*(this.effectKind==='unfold'?.7:1.8);this.fx.scale.setScalar(this.effectKind==='unfold'?Math.sin(Math.min(t,1)*Math.PI)*.8+.4:1+Math.sin(t*Math.PI)*.2);if(t>=1)this.clearEffect()}
  this.renderer.render(this.scene,this.camera);
 }
 diagnostics(){const sorted=this.frames.slice().sort((a,b)=>a-b),q=(v:number)=>sorted[Math.floor((sorted.length-1)*v)]??0;const gl=this.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return{renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),viewport:[innerWidth,innerHeight],drawingBuffer:[gl.drawingBufferWidth,gl.drawingBufferHeight],frameMs:{p50:q(.5),p95:q(.95),p99:q(.99),samples:sorted.length},resources:{...this.renderer.info.memory,calls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles},loadedAtMs:this.loadedAt,loadingErrors:this.loadingErrors,position:{...this.position},camera:{yaw:this.yaw,pitch:this.pitch,distance:this.distance},effectChildren:this.fx.children.length}}
}


